# Based on https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
name: Build Docs
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

    - name: Setup Lua
      uses: hishamhm/gh-actions-lua@fc6f8de246f8c01f6e1a56a1b851143e23370ff3 # master
      with:
        luaVersion: "5.5"

    - name: Setup LuaRocks
      uses: hishamhm/gh-actions-luarocks@95d2308a0aff36ad31ebadca493ed14853399842 # master
      with:
        luaRocksVersion: "3.13.0"

    - name: Setup dependencies
      run: luarocks install --only-deps ldoc-dev-1.rockspec

    - name: Build docs
      run: make doc-site

    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
