# Based on https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
name: Build Docs
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup Lua
      uses: hishamhm/gh-actions-lua@fc6f8de246f8c01f6e1a56a1b851143e23370ff3 # master
      with:
        luaVersion: "5.5"

    - name: Setup LuaRocks
      uses: hishamhm/gh-actions-luarocks@95d2308a0aff36ad31ebadca493ed14853399842 # master
      with:
        luaRocksVersion: "3.13.0"

    - name: Setup dependencies
      run: luarocks install --only-deps ldoc-dev-1.rockspec

    - name: Build docs
      run: make doc-site

    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
